### ISSUE TITLE
Errors and Solutions

### ISSUE THREAD

**Issue by SimonErich** [nuwave/laravel-graphql-relay#1]
Hey Christopher,

thank you for this package. It's awesome. :)

While trying to play around with it and relay-starter-kit I stumbled upon a few small things and thought it might help some people, who experience the same.
(maybe you could also add a "errors and solutions" page to the wiki. I was about to do it, but didn't want to bring chaos into your repo)

Just using this package for the backend works fine, but when I tried to copy the schema.json file to the frontend I got the following two errors:

**1.) Mutation fields must be an object with field names as keys or a function which returns such an object.:**
The problem here was that I didn't create any mutations yet.
The solution was to just add one mutation to the array in config/graphql.php and then this error was gone.
Although this will probably not be relevant for real projects, it kind of took me a couple of minutes to find the solution.
(a condition here would be fine for beginners, but I tried to fix that and create a push request, but realized this must be solved in graphql-php)

**2.) Cannot query field "viewer" on "Query":**
This one actually took a while. The problem here is that Folklores laravel-graphql has the following code in their examples:

```
class UsersQuery extends Query {

    protected $attributes = [
        'name' => 'Users query'
    ];
```

changing the name from format "Viewer query" to just "viewer", solves this issue and creates the schema.json correctly.

With those 2 changes I could use the same schema.json for the server and client.

**Comment by chrissm79** [comment]
@SimonErich 
1. Really good point here, I forgot that I had to create a minimum of at least one mutation in order to avoid errors. I'll add that to the Wiki. 
2. Yeah, the naming conventions threw me a bit as well. 

Both point out the fact that I need to improve documentation quite a bit. It will some time with the workload I currently have, but I intend to build out the Wiki with some more examples and possibly a series of videos (I haven't seen many examples that go over mutations from start to finish). 

I'm going to reopen until the documentation has been written out. Thanks for the feedback!

**Comment by SimonErich** [comment]
@chrissm79 thank you.
I'll try to inform the community about stuff where I get stuck, to help the process ;)

Right now I'm having trouble to get mutations to work.
I always get the error:
`"Variable $input_0 expected value of type AddTodoInput! but got: null."`

Any idea where that might come from or do you have a simple working example (relay and graphql together) at hand for me to debug my code?

thanks

**Comment by chrissm79** [comment]
I think this might be due to this issue ([#17](https://github.com/Folkloreatelier/laravel-graphql/issues/17)). I had to create my own controller, but it was very simple:

``` php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use GraphQL;
use App\Http\Requests;
use App\Http\Controllers\Controller;

class GraphQLController extends Controller
{
    public function index(Request $request)
    {
        $query = $request->get('query');
        // By default, laravel-graphql looks for 'parameters' instead of 'variables'
        $variables = $request->get('variables');

        if (is_string($variables)) {
            $variables = json_decode($variables, true);
        }

        return GraphQL::query($query, $variables);
    }
}
```

Then in your graphql.php config file:

``` php
// ...
'controllers' => '\App\Http\Controllers\GraphQLController@index',
```

Let me know if that works!

**Comment by SimonErich** [comment]
Hey Chris,

thank you for your snippet.
I tried it and it seems to work better, but now I'm getting this error.
`Variable $input_0 expected value of type AddTodoInput! but got: {"AddTodoInput":{"title":"New Todo: 1448615436113"},"clientMutationId":"0"}.`

Any ideas or am I missing something here? :)

**Comment by chrissm79** [comment]
Is this in Relay, or in GraphiQL?

Can you show me the "variables" that are being sent to the server?

**Comment by SimonErich** [comment]
The variables here are the variables that are being sent to the server.

Heres my code:
https://github.com/SimonErich/relay-test-server
https://github.com/SimonErich/relay-test-server

**Comment by chrissm79** [comment]
I copied your mutation class and was able to get the mutation to work. I used GraphiQL just to mock out a request, but this is how Relay should send a mutation query to your server:

**Query**

``` graphql
mutation AddToDoQuery($input: AddTodoInput!) {
  addTodo(input: $input) {
    clientMutationId
    todo {
      id
      title
    }
  }
}
```

**Variables**

``` json
{
  "input": {
    "title": "Work on Documentation",
    "clientMutationId": "1"
  }
}
```

If you're testing things manually, the clientMutationId is something that Relay will inject into the variables payload for you, so you can use any string you would like (read more [here](https://facebook.github.io/relay/graphql/mutations.htm#sec-Mutation-inputs)).

_Note: I used one of my own types to return a response, so I omitted the "title" field from the request query_
<img width="1284" alt="screen shot 2015-11-28 at 6 09 35 am" src="https://cloud.githubusercontent.com/assets/1976169/11452044/a5ae40bc-9596-11e5-96c3-2375df2ecdf2.png">

**Comment by SimonErich** [comment]
sorry @chrissm79 . Completely forgot about it until now.
And i just noticed, I sent the same link twice.
What I meant to send was the client side as well.
https://github.com/SimonErich/relay-test-client

I can't seem to get it working properly. But I guess I'm doing something wrong.
Any ideas?

**Comment by bcarroll22** [comment]
@SimonErich, have you done anymore work on an example?

I think it would probably be most beneficial for this application to have a mirror of the graphql-relay-js [Star Wars test examples](https://github.com/graphql/graphql-relay-js/tree/master/src/__tests__).

Once we resolve any issues with the PR I submitted yesterday and get it merged in, I'd like to start working on making a good bit of documentation for the package.

**Comment by alexwhb** [comment]
@chrissm79 Is there a way to get access to a EdgeType without redefining it? I'm tying to do something like this: 
```
type AddTodoPayload {
  todoEdge: TodoEdge
  viewer: User
  clientMutationId: String!
}
```
```
type TodoEdge {
  node: Todo
  cursor: String!
}
```

and I want access to the Todo Edge, but I can't seem to get it. I tried `GrapghQL::edge('TodoEdge')` but it does not work. And this edge does exist in my schema. I'm just trying to use it in my mutation. Any advice?

**Comment by spawnia** [comment]
This project is deprecated in favor of https://github.com/nuwave/lighthouse
