### ISSUE TITLE
One-to-One Connections

### ISSUE THREAD

**Issue by davidstoker** [nuwave/laravel-graphql-relay#19]
The `resolve` method in `ConnectionResolver` is currently expecting items to be a Collection. If I pass a one-to-one connection in my `GraphQL::connection` like an Eloquent belongsTo or hasOne relationship then an exception is thrown in `RelayConnectionType` line 145 when it tries to set `$item->relayCursor = $encodedCursor;` where `$item` is not an object in this case.

It looks like a check like this would need to be added to ensure that a collection is passed to the Paginator in `resolve` as opposed to the individual object returned by the Eloquent relationship and the `getItems` method  in `ConnectionResolver`.

```
$items = $this->getItems($root, $info, $name); 
if (!($items instanceof Collection)) { 
    $items = new Collection([$items]); 
} 
```

**Comment by davidstoker** [comment]
Ahh, on further research, for a one-to-one it relationship it would make more sense to define a field and return the GraphQL type versus making a connection since pagination and other functionality of a connection aren't needed. This issue should probably be closed and ignored then.

**Comment by chrissm79** [comment]
You are correct, in that case you would just want to return a GraphQL field. I _seriously_ need to make a video series to go over how to get started and all the little gotchas for certain edge cases. I'll update the README once I've pushed some tutorials.
