### ISSUE TITLE
Any example repos?

### ISSUE THREAD

**Issue by livemixlove** [nuwave/laravel-graphql-relay#2]
I would love to see an example application that uses laravel-graphql-relay.  Are there any public git repos  to check out?

**Comment by chrissm79** [comment]
Not at the moment, but I am thinking of creating a series of videos that I'll put up on YouTube.  It will go over creating a GraphQL server w/ Laravel, Relay integration, and working w/ React Native. I thought it would be cool to use Laravel as a backend for a mobile application. I might make an additional video w/ React but my experience w/ Webpack & boilerplates has been painful.

I'm waiting for a new release for [React Native](https://github.com/facebook/react-native/issues/2985) that let's [Relay](https://github.com/facebook/relay/issues/26) work out of the box. Hopefully this weekend I can get started on the GraphQL video. Let me know if there are any topic in particular you'd like to see and I'll try to incorporate them.

Thanks!

**Comment by andrekovac** [comment]
@chrissm79 Great idea! I'll be the first one to watch!

I'm especially interested in how to integrate GraphQL and Laravel on the back-end with a React Native mobile app. Also waiting for the release which lets Relay to work out of the box!

**Comment by spawnia** [comment]
This project is deprecated in favor of https://github.com/nuwave/lighthouse
