### ISSUE TITLE
Camel case option not working as expected

### ISSUE THREAD

**Issue by alexwhb** [nuwave/laravel-graphql-relay#23]
Hey, first off just wanted to say I seriously love what you've done with this project. It's awesome! I've been integrating it into a work project the last few days. I do have one problem however. It could just be me being ignorant, but I'm hoping to change all my model field names to camel case, and from what I read in the docs I got the impression that's what this does: 

```
'eloquent' => [
    'path' => 'App\\Models',
    'camel_case' => true
]
```

when I enabled that it did not change anything as far as I'm aware. I tried updating relayFields() method on one of my data types, and when I set a field name such as this: 

```
 'first_name' => [
                'type' => Type::string(),
                'description' => 'some description'
            ],
```

to something like this: 

```
 'firstName' => [
                'type' => Type::string(),
                'description' => 'some description'
            ],
```

it no longer resolves. Am I miss understanding how that works?

**Comment by chrissm79** [comment]
Hey @alexwhb, thanks for the support! 

I should've put some more documentation inside the config file to help explain some of the options, this one certainly does give the impression that it will do the work automatically. However, the camel_case option can be used _along with_ the [Eloquence](https://github.com/kirkbushell/eloquence#camel-case-all-the-things) package.

 At this point, the only purpose it serves is to camel case your fields when you choose to generate a Type from a Eloquent Model ([not currently documented](https://github.com/nuwave/laravel-graphql-relay/blob/master/src/Commands/TypeMakeCommand.php#L80)). So, for instance, if you model that has a DB column named "first_name" for your User model it would set the name of the field in the UserType to "firstName".

FYI, I have been insanely backed up with work but [Lighthouse](https://github.com/nuwave/lighthouse) will serve as the successor to this package and I'll release a screencast to go along with it to provide an overview of how it works... as soon as I can find the time :-)

**Comment by alexwhb** [comment]
@chrissm79 Thank you so much for your quick response and info. Much appreciated!

**Comment by SimonErich** [comment]
@chrissm79 why the change to a new package if I might ask?

What might be interesting as well are the new details about "relayjs 2"
(see https://www.youtube.com/watch?v=OEfUBN9dAI8 )

**Comment by chrissm79** [comment]
@SimonErich Thanks for the link to the vid, I've seen the slides and was waiting for it to be released so I could watch it, can't wait to see what the new mutation api looks like!

This package got to be quite the monolith and I wanted to have a fresh start that began with testing (instead of trying to start injecting tests after a very large code base was already in place). With testing I could feel more confident that any additions I made along w/ any PRs weren't going to break functionality.

I hate that it will force people to make changes in the structure of their own apps but (in my opinion) it will make things easier to work with down the road.

**Comment by spawnia** [comment]
This project is deprecated in favor of https://github.com/nuwave/lighthouse
