### ISSUE TITLE
Unable to get cursor on custom connection resolution. 

### ISSUE THREAD

**Issue by alexwhb** [nuwave/laravel-graphql-relay#24]
Just started running into this problem. I'm trying to resolve my library cursor when doing this custom connection resolution, but I'm getting this error: `Cannot return null for non-nullable type.` I'm assuming that has something to do with the model integer id to string id conversion? I'm wondering if there's a good solution. I'm doing a custom connection resolution on my User model like so: 

```
    public function relayFields()
    {
        return [
            'id' => [
                'type' => Type::nonNull(Type::id()),
                'description' => 'The id of the library'
            ],
            'libraries' => GraphQL::connection('Library', function ($userModel, $args, $info) {
                $items = Library::all();
                if (isset($args['first'])) {
                    $total = $items->count();
                    $first = $args['first'];
                    $after = $this->decodeCursor($args);
                    $currentPage = $first && $after ? floor(($first + $after) / $first) : 1;

                    return new Paginator(
                        $items->slice($after)->take($first),
                        $first,
                        $currentPage
                    );
                }

                return new Paginator(
                    $items,
                    count($items),
                    (count($items) > 0 ? count($items) : 1)
                );
            })
        ];
    }
```

here's what my query looks like: 

```
{viewer(id: 1){
  libraries(first: 3){
    edges{
      node{
        id
        }
      cursor
      }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
}
}
}
```

everything resolves perfectly except for the cursor.

**Comment by chrissm79** [comment]
@alexwhb That looks correct... So if you remove the "cursor" field from the query it works without errors?  You may want to try logging out some of the variables created [here](https://github.com/nuwave/laravel-graphql-relay/blob/1cf05d386a12e0176c220981b0e341bebdadabf5/src/Support/Definition/RelayConnectionType.php#L131-L152) (it injects the cursor into the edge) and see if something isn't resolving correctly.

Alternatively I can take a look at the repo and may be able to assist if you prefer.

**Comment by alexwhb** [comment]
@chrissm79 Hey sorry it took me so long to get back to you. That is correct. That's the only field that is messing things up. I did resolve this issue by adding another field on my model and returning from there. This is what I did: 

on my **User model**:

```
    protected $appends = ['libraries'];

    public function getLibrariesAttribute(){
        return Library::all();
    }
```

On my **User Type**: 

```
    public function relayFields()
    {
        return [
            'id' => [
                'type' => Type::nonNull(Type::id()),
                'description' => 'The id of the library'
            ],
            'libraries' => GraphQL::connection('Library', 'Libraries'),
        ];
    }
```

and that worked. It resolves the courser and everything. So my thinking is something is not getting injected properly when I was writing it in that other form. I may run into this situation again where I don't really want to put that field on my model, in which case I'll do more hunting around for the problem.

**Comment by chrissm79** [comment]
Well, I'm glad to hear you got it resolved! It looks strange because what you had should've worked (it's essentially exactly what the default resolver does). If you run into issues again let me know and hopefully we can get to the root of the problem and resolve it.

Thanks @alexwhb!

**Comment by alexwhb** [comment]
@chrissm79 Thank you very much. :+1: I'll let you know if I run into it again. I'm getting pretty familiar with your source code, so I might be able to track it down.

**Comment by alexwhb** [comment]
@chrissm79 Wow I'm an idiot! I figure it out... I was using `Illuminate\Pagination\Paginator` not `Illuminate\Pagination\LengthAwarePaginator` and that's what caused it. Just tested it with another field that I need to resolve without putting it on a model and it worked like a charm. Thanks again for your help and assistance. Your project is awesome!

**Comment by chrissm79** [comment]
Ha! I did the exact same thing when building the auto-resolver and it took me hours to figure out what was going on! Thankfully you were able to track down the issue, it really had me wondering. Let me know if you have any other questions!

**Comment by spawnia** [comment]
This project is deprecated in favor of https://github.com/nuwave/lighthouse
