### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by sandervanhooft** [nuwave/laravel-graphql-relay#26]
Hi,

Is this project still under active development?

**Comment by chrissm79** [comment]
@sandervanhooft  this project will be depreciated when I complete the docs for  [Lighthouse](https://github.com/nuwave/lighthouse). I'm **hoping** to get it done this weekend. Thanks!

**Comment by sandervanhooft** [comment]
Seems like a mysterious project without the docs :). Will keep an eye out,
thanks for your update!

**Comment by spawnia** [comment]
This project is deprecated in favor of https://github.com/nuwave/lighthouse
