### ISSUE TITLE
Update graphql version

### ISSUE THREAD

**Issue by andynoelker** [nuwave/laravel-graphql-relay#3]
First of all, this looks like such a wonderful project!

Currently the composer.json requires `^0.3.3` of `folklore/graphql`. Because of how the caret operator [treats pre-1.0 versions](https://getcomposer.org/doc/articles/versions.md#caret) this will never match anything higher than `0.3.9` but `folklore/graphql` is already up a minor version! Could you please update the composer.json so that it accepts all `0.*` versions of `folklore/graphql`? I can't even install this package because I already am using the higher version. Thanks!

**Comment by chrissm79** [comment]
Thanks for the heads up! I updated the dependencies and tagged 0.1.5. I'll be the first to admit that this project has been a bit neglected recently with the holidays, but I hope to get started on some videos this weekend that goes over using Laravel/GraphQL/Relay together. Let me know if you run into any issues!

**Comment by andynoelker** [comment]
Hey thanks so much, now the package downloads just fine!
