### ISSUE TITLE
New Relay package based on webonyx/graphql

### ISSUE THREAD

**Issue by bcarroll22** [nuwave/laravel-graphql-relay#5]
Hey @chrissm79, I just saw that webonyx bumped the version of their GraphQL package today, and they also updated their README to list some complimentary resources. This package was listed on the page, as well as one other Relay package that's an "exact port of the original graphql-relay js implementation from Facebook."

With the soon-landing changes that will make React Native compatible with Relay, how possible do you think it would be to work together with this package to get subscriptions implemented in a fully spec-compliant relay server? I think there would at least be great value in you contributing to that conversation, because you've spent so much time in the weeds with implementing Relay with the Laravel package.

[Here's the link to the issue that's currently open on that package](https://github.com/ivome/graphql-relay-php/issues/1).

Laravel's event system would definitely work awesome with subscriptions, so I'd like to help however possible and maybe combine forces if we can here to get Relay fully implemented ASAP.

**Comment by chrissm79** [comment]
I took a look at that as well, looks like it just needs some documentation but it's a well built package for sure! I'm going to dig into the connections and see how they are resolved as we have eager loading available in Eloquent (but there's also some N+1 issues that need to be addressed). I might continue to build out this package or do an overhaul and fully utilize graphql-relay-php with some Laravel friendly functionality. I would really like to get to a point where you just register your models, queries and mutations and the package takes care of registering types and connections automatically.

I've been eagerly awaiting the landing of subscriptions in GraphQL and Relay. Have they landed a complete implementation of subscriptions in Relay yet? The last bit of info I came across was on the Discord channel that some people were fiddling around with different types of implementation but there's nothing concrete yet. 

You're right though, Laravel's event/broadcasting seems like a terrific fit for what needs to be accomplished w/ Subscriptions. From what I've gathered so far, it looks like we might need to incorporate something like [Rachet's](http://socketo.me/) WAMP server. Reason being is that we may need session data that (from my limited knowledge so far) we can't get from a Node/Redis setup.

**Comment by bcarroll22** [comment]
Does the pure PHP Relay implementation expand on the webonyx package in such a way that the Folklore package can enable Relay as long as it's installed?

Eager loading is easy using the ResolveInfo right? If the array key is an array, it's a relationship, and you can keep nesting into it and finding keys that are arrays to build your load string? Or you could write a base resolve method that loads any array keys that are arrays. That would still be much faster than N+1 queries.

I haven't seen a "concrete" thing either I guess, so that does make it kinda hard.

Ugh, I _hated_ setting up a Ratchet WAMP server. It'd almost be worth building some kind of bridge from node to check your Laravel auth to not have to use that... ZeroMQ was hard to set up, as you said in the other post.

I love this package by the way, I'm using it to build a GraphQL API right now. I've made some modifications to it, but unfortunately it would take some work to submit them back as a pull request because I'm using hacklang and Lumen.

**Comment by chrissm79** [comment]
@bcarroll22 just FYI, I created a new issue ( #6 ) which is a starting point for subscriptions in Laravel/GraphQL/Relay.
