### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by chrissm79** [nuwave/laravel-graphql-relay#6]
For the time being this is just a placeholder, but I thought I'd use it to get a conversation started about implementation. At the time of opening this issue, Subscription Types have not been fully adopted into Relay/GraphQL, but it seems to be on the horizon. 

PHP isn't known for "real time" features, which include websockets. There will likely be a need to integrate some sort of 3rd party solution. Thankfully, Laravel make broadcasting events easy, we just need to figure out how to send the appropriate data to users who have subscribed to certain channels. This means that we will need Authorization/Authentication which adds a bit of complexity. So far, I've found three possible solutions, which are as follows:

1.[Redis/Node/Socket.io](https://laracasts.com/series/real-time-laravel-with-socket-io): Easy to setup but it doesn't give us access to any session data (Node can't read the session data coming from the Client/Laravel). 
2. [Ratchet](http://socketo.me/docs/push): Has push integration and would allow to access data about the user. However, it relies on ZeroMQ which can be quite a pain point for some (at least it was for me).
3. 3rd Party Service: [Pusher](https://pusher.com/features), for example, could potentially be utilized, but it does come at a cost. It's also not certain that a service such as this could be used with Subscriptions in Relay/GraphQL (although I don't see why not).

Reading through how Pusher handles [Private Channels](https://pusher.com/docs/client_api_guide/client_private_channels), it leads me to believe that it might be a viable solution. It also gives me the idea that we could do something similar w/ Node/Redis. For instance, when a user subscribes to a channel, it sends a token along with the request. Node hits an endpoint on the Laravel server which provides a response telling Node if the user is authorized to listen to the channel or not. If this something that would work, we would want to make the setup easy for developers unfamiliar w/ Node. Such as:

_Creates a node server.js file and places it in the public folder (and possibly installs packages automatically)_

``` bash
php artisan relay:server:generate
```

_Starts the node server and listens for subscriptions/events_

``` bash
php artisan relay:server:run
```

The config file would hold the port, node server location and any additional details would would need.

If you have any insight you can provide that gives some details on how Relay/GraphQL intends to implement Subscriptions please share!

**Comment by bcarroll22** [comment]
To me, this seems like a thing that we should give suggestions on instead of trying to have a built in solution. Most likely, some people that want to use this package will already be using some form of broadcasting, and we wouldn't want to impose too much on what they're currently doing.

**Comment by bcarroll22** [comment]
I guess looking into it more, there's also a big bottleneck that the webonyx package doesn't have any form of subscriptions support also.

**Comment by bcarroll22** [comment]
@chrissm79 is it worth waiting around for the official spec to be released for subscriptions, or would it be better to just come up with an official suggestion for how to make this work with the event system that already exists in Laravel?

**Comment by chrissm79** [comment]
@bcarroll22 Waiting to see if anything get's announced at [React Europe](https://www.react-europe.org/). If we still don't have a clear path then I'll look into adding support/docs for using Laravel's event broadcasting to trigger [forceFetch](https://facebook.github.io/relay/docs/api-reference-relay-container.html#forcefetch). I haven't looked into this too deeply yet (been working on [revamping this package](https://github.com/nuwave/lighthouse/tree/master) with much heavier testing), but I think it might give us what we need to at least re-fetch a query when there's been an update.

**Comment by spawnia** [comment]
This project is deprecated in favor of https://github.com/nuwave/lighthouse
