### ISSUE TITLE
Set up StyleCI for the repo

### ISSUE THREAD

**Issue by bcarroll22** [nuwave/laravel-graphql-relay#8]
To ensure we keep up on the coding standards here, we should probably set up a StyleCI hook for this repo. Laravel uses it, and it does a good job. It would be nice to do style checks before merging in PRs. If I remember correctly, StyleCI can also make style changes and push them back into the repo, and that's pretty cool.

I'd recommend pulling in the [.php_cs config file](https://github.com/laravel/framework/blob/5.2/.php_cs) from Laravel so we match their framework coding style. 

Any other input on that would be awesome, also.

**Comment by spawnia** [comment]
This project is deprecated in favor of https://github.com/nuwave/lighthouse
