### ISSUE TITLE
Use Eloquent models for Type Generation

### ISSUE THREAD

**Issue by chrissm79** [nuwave/laravel-graphql-relay#9]
We should be able to use Eloquent models to generate GraphQL Types for us. I am currently working on the following proposal, and I wanted to create this issue to start a discussion about implementation or questions/feedback.
## Eloquent types

Generally you will have a GraphQL Type representing an Eloquent model. To ease this process, there will be 3 ways in which you can create a type based on an Eloquent model.
### Auto-Generate

All you have to do is define the type in your schema file and you're done. This is the easiest way to generate a GraphQL type based on an Eloquent model. However, **it is also the slowest**. This is because it will look at the database and generate fields based on the columns and the column's type. 

In your schema.php file:

``` php
<?php
//...

// Register the type 'user' from the Eloquent User model.
GraphQL::type('user', App\Models\User::class);
```

(_You can add custom resolve methods for fields inside your model._)

``` php
<?php
// ...
class User extends Model
{
    //...
    public function resolveFirstNameField($user)
    {
        return ucfirst($user->first_name);
    }
}
```

(**Note:** Auto-generating types does not include relationships.)
### Define Type inside model

Instead of auto-generating your fields, you can define them inside your model. To do so, create a `graphqlFields` method that returns an array of fields. You can also include connections (if they are registered in your `schema.php` file).

``` php
<?php

class User extends Model
{
    //...
    public function graphqlFields()
    {
        return [
            //...
            'friends' => [
                'type' => GraphQL::connection('user')
            ]
            // ...
        ];
    }

    //...
    public function resolveFriendsField($user, array $args)
    {
        $take = $args['first'];
        $after = $args['after'] ?? null;
        //...
    }
}
```

_(To register a connection, add the following to your schema.php file:)_

``` php
<?php

// Register the connection 'users' from the Eloquent User model.
GraphQL::connection('users', App\Models\User::class);
```
### Generate Type Class from Eloquent Model

If you want to keep your eloquent models clean of GraphQL specific definitions, you can generate a Type class based on your Eloquent model.

From the command line:

``` bash
php artisan make:relay:type --model=App\Models\User
```

Register the type in your schema.php file:

``` php
GraphQL::type('user', App\Http\GraphQL\Types\UserType::class);
```

Running the command will generate the following Type class:

(**Note:** Generating a type class does not include relationships.)

``` php
<?php

namespace App\Http\GraphQL\Types;

use GraphQL;
use GraphQL\Type\Definition\Type;
use Nuwave\Relay\Types\RelayType;
use GraphQL\Type\Definition\ResolveInfo;

class UserType extends RelayType
{
    /**
     * Attributes of Type.
     *
     * @var array
     */
    protected $attributes = [
        'name' => 'User',
        'description' => '',
    ];

    /**
     * Get customer by id.
     *
     * When the root 'node' query is called, it will use this method
     * to resolve the type by providing the id.
     *
     * @param  string $id
     * @return User
     */
    public function resolveById($id)
    {
        return \App\Models\User::findOrFail($id);
    }

    /**
     * Available fields of Type.
     *
     * @return array
     */
    public function relayFields()
    {
        return [
            'firstName' => [
                'type' => Type::string(),
            ],
            'lastName' => [
                'type' => Type::string(),
            ],
            'email' => [
                'type' => Type::string(),
            ],
            // ...
        ];
    }
}
```

**Comment by SimonErich** [comment]
I really like the idea and it should definitely be the goal to reduce boilerplate code and multiple definitions with a solution like that.

Just a few thoughts on that:

**Auto generated types:**
By "slow" you mean during runtime or when running the generator?
Maybe we could find a way there to make it possible to calculate during runtime (for develop mode), but add a caching functionality of that via artisan optimize or a standalone artisan command like:

> artisan relay:cache:models

**resolveFriendsField**
Do you think it would make sense to use Eloquent Accessors and Mutators for that, or do you think that this could be a problem?
I'm not really sure. It's just a thought.

**Generate Type Class from Eloquent Model**
Why would you exlude the relationships?
Do you think it's too complicated?
I personally would love that.
Even if the result is not perfect and I would have to tweak it, but it would save a lot of time and you would just have to run the command and then clean up a little bit. :)

**Comment by chrissm79** [comment]
Hey @SimonErich,

**Auto generated types:**
I like that idea. Maybe on the first pass I exclude it just to get the updates pushed, but that would definitely be beneficial!

**resolveFriendsField**
Well, when you resolve a field in GraphQL you are passed the root object, the arguments and the resolve info, so I don't think it would work as a mutator. Additionally, everyone may want to resolve these differently. For instance you may use a different method if your relationship could potentially have < 100 items compared another relationship that may have 1000s (I'm working on a workaround for the latter).

**Generate Type Class from Eloquent Model**
Connections can definitely be included in your Type model, they just can't be auto-generated. When the artisan command is run, it creates a new instance of the model and populates the fields by the column information found in the model's table. However, it is an empty model, so there is no way for me to get all of the possible relationships. In other words:

``` php
$user = new App\User();
$user->relations; // <---- This is empty since it is an empty model

$user = App\User::find(1);
$user->relations; // <---- This will give us a list of relations for this particular user
```

Thanks for the feedback and let me know if you see any other areas that can be improved on!

**Comment by SimonErich** [comment]
**resolveFriendsField:**
Ah sorry, I've just looked at your code on a bigger screen and saw that the resolveFriendsField is a connection. I thought it was a virtual type field like "fullname". ;) Sorry my fault.

**Generate Type Class from Eloquent Model:**
Well that is true of course, but if we generate those relationships if we got an empty model and foreign keys.
(like this package does: https://github.com/pepijnolivier/Eloquent-Model-Generator )
I've used this in a couple of projects and the results aren't perfect, but it's a good scaffolding tool if you have a lot of tables and have to think about complex relations.

This is just a quick thought and certainly something for the future. ;)
Are you working on this already?
If so, I'll wait for your implementation and will try those things.

Like I said. I will (hopefully) have more time soon to contribute to this package. :)

**Comment by chrissm79** [comment]
Nice!! I haven't seen that package before. I'll dig around and see if I can get away with not using it as a dependency.

This is currently being worked on, but on the side. My 9-5 limits my time a bit. I would like to aim for the end of this week, but we'll see. I don't intend to work on my application that uses this package until the updates are done, just for some added incentive :-)

**Comment by chrissm79** [comment]
I ran into an issue w/ caching & connections (I might create a separate issue for this), so for the time being the EloquentType won't automatically handle relationships. Good news is that defining a relationship on a type will be as quick as `GraphQL::connection('user', Closure/relationshipName)` which ought to make things pretty painless. 

Any auto-generated fields will be cached and the developer can run `php artisan relay:cache` to regenerate a cache of all EloquentType fields.

This functionality will be included in the next version bump which will take place after I have the new documentation ready to go.

**Comment by SimonErich** [comment]
Yeah I've noticed a lot of activity on the package. Really really cool.
Looking forward to trying everything and I will play around with connections as well.
Maybe I can find a workaround and sent a pull request. :)

Thank you for your awesome work so far. :)

**Comment by SimonErich** [comment]
Just a quick question:
how and where do you define connections right now?
I've tried setting them in the schema file, but that doesn't work like that:
`
    Relay::group(['namespace' => 'Types'], function () {
        Relay::type('attraction', 'AttractionType');
        Relay::type('category', 'CategoryType');
        Relay::connection('AttractionType', "CategoryType");
    });`

**Comment by spawnia** [comment]
This project is deprecated in favor of https://github.com/nuwave/lighthouse
